name: ACR Login Docker Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: azurecr09.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker Container
      run: |
        docker build . -t azurecr09.azurecr.io/gh-react-example:${{ github.sha }}
        docker push azurecr09.azurecr.io/gh-react-example:${{ github.sha }}
