name: ACR Login Docker Push

on: [push]

jobs:
  job1:
    name: Push Docker to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: azurecr09.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker image to ACR
      run: |
        docker build . -t azurecr09.azurecr.io/gh-react-example:${{ github.sha }}
        docker push azurecr09.azurecr.io/gh-react-example:${{ github.sha }}
